name: wimax_flutter
description: تطبيق اختبار أمان الشبكات اللاسلكية باستخدام Flutter/Dart

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: "3.16.x"

dependencies:
  flutter:
    sdk: flutter
  permission_handler: ^10.2.0
  path_provider: ^2.1.1
  http: ^0.15.0
  flutter_secure_storage: ^5.0.2
  csv: ^5.0.1
  json_serializable: ^6.6.0
  connectivity_plus: ^3.0.2
  provider: ^6.1.1
  cloud_firestore: ^4.14.0
  firebase_auth: ^4.17.0
  google_fonts: ^6.1.0
  sign_in_with_apple: ^5.0.0
  url_launcher: ^6.2.5
  share_plus: ^6.3.0
  firebase_core: ^2.17.0
  flutter_local_notifications: ^14.3.0
  tflite: ^1.1.2
  file_picker: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.1.0
  flutter_gen_l10n: ^0.26.0+1

flutter:
  uses-material-design: true
  assets:
    - assets/tools/
    - assets/wordlists/